### ISSUE TITLE
Box version 1.0.9 fails to load HGFS module with vmware

### ISSUE THREAD

**Issue by alex-kaufman** [geerlingguy/packer-ubuntu-1404#16]
The newest version on https://vagrantcloud.com/geerlingguy/boxes/ubuntu1404 hangs when trying to load the HGFS module in vagrant, and never completes.

**Comment by geerlingguy** [comment]
I didn't have this issue in my local testing, at least with VMware Fusion 8. Are you using VMware, and if so, what version, and pro or normal?

**Comment by geerlingguy** [comment]
Also, a workaround is to use NFS for the /vagrant share (instead of native synced folders), or to disable it completely.

**Comment by alex-kaufman** [comment]
I am using vmware fusion 8 pro.  

this issue is likely related:
https://github.com/mitchellh/vagrant/issues/4362#issuecomment-189387740

**Comment by geerlingguy** [comment]
@alex-kaufman - Did you/do you not have the same issue with any older versions of the box (e.g. 1.0.8)? I seem to remember having the issue and switching to NFS solved it for me.

I'm going to close this issue and redirect people to the upstream issue instead... I don't know if it would be easy for me to resolve this downstream of either VMware fixing the issue or Vagrant working around it.

**Comment by alex-kaufman** [comment]
@geerlingguy I have been using this box since version 1.0.4 and while I have had issues with HGFS in the past, those were always if I powered down the box and then try to bring it back up.  This was different in that it occurred when I brought the box up for the first time.  

I simply am using version 1.0.8 of the box now with no issues.

thanks for looking into this and hopefully there will be greener pastures in the future when HGFS isn't  a pain point.

**Comment by geerlingguy** [comment]
@alex-kaufman - Okay; I'll also be tracking the upstream issue... and it looks like simply using 14.04.4 is the major issue:

> The workaround for Kernel auto upgrade does not work for Ubuntu 14.04.4 version. Had to go back to 14.04.3.

So I'll also see if Bento or other major box producers have any solution. Definitely annoying!

**Comment by geerlingguy** [comment]
See also: https://github.com/chef/bento/issues/283

**Comment by geerlingguy** [comment]
And: https://github.com/chef/bento/issues/496

Looks like we might just need to wait until 8.2.0, or until VMware fixes it. I don't want to lock this box in at Ubuntu 14.04.3, and it's likely going to be the same for 16.04 (coming April 21), so my hands are kinda tied :(
