### ISSUE TITLE
Switch back to 14.04.4 or latest if HGFS issues ever resolved

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/packer-ubuntu-1404#18]
It looks like the HGFS issue might be resolved, so I'm going to do some testing. See related: https://github.com/geerlingguy/packer-ubuntu-1604/issues/5

**Comment by geerlingguy** [comment]
It seems that [boxcutter may have given up on Ubuntu 14.04.4 as well](https://github.com/boxcutter/ubuntu/pull/68#issuecomment-224274721), and others commenting in https://github.com/mitchellh/vagrant/issues/6775 are still reporting problems with 14.04.4.

I'm going to keep things on the old version a while longer... maybe someone else will be able to take the time to sort it out elsewhere. In the mean time, I'm going to test on my 16.04 images.

**Comment by geerlingguy** [comment]
[Bento also gave up on 14.04.4](https://github.com/chef/bento/pull/584/files), so yeah... going to just leave this be and lock in 14.04.1 for the foreseeable future. D'oh!

**Comment by it-praktyk** [comment]
Please check https://github.com/it-praktyk/packer-ubuntu-1404/tree/14_04_5_LTS_corrected and https://github.com/it-praktyk/ansible-role-packer-debian . 

For me it works now - I use Fedora 25 x86, Packer 1.0.0, VMware Workstation 12.5.6.

Reboots can be handled in a smarter way: https://serverfault.com/questions/92932/how-does-ubuntu-keep-track-of-the-system-restart-required-flag-in-motd 

I'll prepare a pull requests soon and after that I'll remove from Ansible Galaxy it-praktyk.packer-debian role.

**Comment by geerlingguy** [comment]
@it-praktyk - Nice, please do, and I'll merge ASAP—thanks for taking the time to do this!

**Comment by it-praktyk** [comment]
@geerlingguy , I did some modification for the ansible-role-packer-debian - currently in branch the branch https://github.com/it-praktyk/ansible-role-packer-debian/tree/Variable-to-install-open-vm-tools. A selection of installed tools is based on variable from Packer build configuration.

It's probably impact that other packer builds for Debian and Ubuntu will need to be updated in similar way. 
 What do you think about this?

I tested with Ubuntu 14.04.5 x86_64 - in both modes (open-vm-tools and VMwareTools) and works for me.

**Comment by geerlingguy** [comment]
Switching back now and closing this issue; using the latest kernel may also help with #24... but regardless I'm not using HGFS/VMware anymore.
