### ISSUE TITLE
Tips on using Ansible Galaxy requirements file

### ISSUE THREAD

**Issue by jbarajas** [geerlingguy/packer-ubuntu-1404#20]
I have some roles in my private git instance. I've tried multiple ways to define the git repo w/ oAUTH keys for example and have been unsuccessful. How do you authenticate with a private git repo with Ansible galaxy

**Comment by geerlingguy** [comment]
This is an issue that should be posted against Packer itself; also see if there are any notes on authentication with Galaxy via Packer in the official docs: https://www.packer.io/docs/provisioners/ansible.html and https://www.packer.io/docs/provisioners/ansible-local.html
