### ISSUE TITLE
Overly complex boot command

### ISSUE THREAD

**Issue by rcousens** [geerlingguy/packer-ubuntu-1404#5]
Hi, I used your build as a template for my own purposes. 

I ended up reducing the boot command to the following:

```
      "boot_command": [
        "<esc><wait>",
        "<esc><wait>",
        "<enter><wait>",
        "/install/vmlinuz",
        " auto=true",
        " priority=critical",
        " initrd=/install/initrd.gz",
        " url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg",
        " -- ",
        "<enter>"
      ],
```

and putting the following in my preseed.cfg

```
d-i debian-installer/locale string en_US

d-i console-setup/ask_detect boolean false

d-i keyboard-configuration/modelcode string pc105
d-i keyboard-configuration/layoutcode string us
```

Results are the same as your current configuration but pushes the decision to the preseed.cfg which is easier to maintain/manage.

Cheers!

PS Thanks for the great template to get me started! I've never used Ubuntu before.

**Comment by geerlingguy** [comment]
This seems to work fine with VirtualBox, but the `vmware-iso` configuration gets stuck on the keyboard chooser screen :-/

I'm digging into why this is happening. Hopefully I'll be able to use similar/same boot command for each. Simpler == better!
