### ISSUE TITLE
Unable to use with VMWare Fusion

### ISSUE THREAD

**Issue by acouch** [geerlingguy/packer-ubuntu-1404#7]
When I try and `vagrant up --provider=vmware_fusion` with the following Vagrantfile: https://github.com/NuCivic/ansible-dev-vm/blob/move-to-geerlinguy140/Vagrantfile

I get:

```
$ vagrant up --provider=vmware_fusion
Bringing machine 'devbox' up with 'vmware_fusion' provider...
==> devbox: Box 'geerlingguy/ubuntu1404' could not be found. Attempting to find and install...
    devbox: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
    devbox: Box Version: >= 0
==> devbox: Adding box 'geerlingguy/ubuntu1404' (v0) for provider: vmware_desktop, vmware_fusion, vmware_workstation
    devbox: Downloading: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box
The box you attempted to add doesn't match the provider you specified.

Provider expected: vmware_desktop, vmware_fusion, vmware_workstation
Provider of box: virtualbox
```

It says the provider of the box is virtualbox, even I I use the URL `http://files.midwesternmac.com/boxes/VMware-ubuntu1404-104.box`

Any idea what the issue is? Thanks.

**Comment by geerlingguy** [comment]
You need to use: `vagrant up --provider=vmware_desktop` (the generic name for all the VMWare platforms, since Fusion is only for Mac OS X).

**Comment by acouch** [comment]
OK. Thank you. Great work on all of this.
