### ISSUE TITLE
20GB is not that much

### ISSUE THREAD

**Issue by ryck** [geerlingguy/packer-ubuntu-1404#9]
Because is a dynamic drive, something bigger, like 80GB would make more sense...

**Comment by geerlingguy** [comment]
"not that much" is a relative term. when you're building these boxes on a laptop with an SSD with only 20-30 GB free space, 20 GB is a pretty decent amount of space :)

But I see your point, and will consider changing the default.

**Comment by ryck** [comment]
Yeah, you are right, it's all relative, but setting it to 100GB won't use 100GB right away, right? 100Gb would be like a hard limit :) We are using your drupal vm (fantastic work, btw) and 20GB is not that much when you want to have several big ddbb, for example.

And 100GB was just an example, btw :)

**Comment by geerlingguy** [comment]
I'm setting the disks on all my boxes to 80 GB now, and rebuilding all the boxes for Vagrant Cloud/Atlas. Should be up sometime over the weekend.

**Comment by ryck** [comment]
Thanks!

**Comment by geerlingguy** [comment]
Boxes are all built and tested, I'm waiting for the loooong upload to complete, then I'll be adding them all to Atlas Cloud.
